# This file is auto-generated by GitHub Actions
# Manual edits will be overwritten on next release
# To update manually, see RELEASE_PROCESS.md

class QuickcodeCli < Formula
  desc "QuickCode API CLI tool"
  homepage "https://github.com/QuickCodeNet/quickcode.cli"
  url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.0/quickcode-cli-osx-arm64-v1.0.0.tar.gz"
  sha256 "PLACEHOLDER_ARM64_SHA256"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.0/quickcode-cli-osx-arm64-v1.0.0.tar.gz"
      sha256 "PLACEHOLDER_ARM64_SHA256"
    else
      url "https://github.com/QuickCodeNet/quickcode.cli/releases/download/v1.0.0/quickcode-cli-osx-x64-v1.0.0.tar.gz"
      sha256 "PLACEHOLDER_X64_SHA256"
    end
  end

  def install
    bin.install "quickcode"
  end

  test do
    system "#{bin}/quickcode", "--version"
  end
end

